# -*- coding: utf-8 -*-
import json, os

script_dir = os.path.dirname(os.path.abspath(__file__))
data_file = os.path.join(script_dir, '..', 'public', 'data', 'curriculum.js')

with open(data_file, 'r', encoding='utf-8') as f:
    s = f.read()

data = json.loads(s[26:-2])  # strip "window.__curriculum = " and trailing ";"

translations = {
    "responsive-web-design": "반응형 웹 디자인",
    "basic-html-and-html5": "HTML5 기초",
    "basic-css": "CSS 기초",
    "applied-visual-design": "시각 디자인 응용",
    "applied-accessibility": "접근성 적용",
    "responsive-web-design-principles": "반응형 웹 디자인 원칙",
    "css-flexbox": "CSS 플렉스박스",
    "css-grid": "CSS 그리드",
    "javascript-algorithms-and-data-structures": "JavaScript 알고리즘 및 자료구조",
    "basic-javascript": "JavaScript 기초",
    "es6": "ES6",
    "regular-expressions": "정규 표현식",
    "debugging": "디버깅",
    "basic-data-structures": "기본 자료구조",
    "basic-algorithm-scripting": "기본 알고리즘",
    "object-oriented-programming": "객체 지향 프로그래밍",
    "functional-programming": "함수형 프로그래밍",
    "intermediate-algorithm-scripting": "중급 알고리즘",
    "front-end-libraries": "프론트엔드 라이브러리",
    "bootstrap": "부트스트랩",
    "jquery": "제이쿼리",
    "sass": "Sass",
    "react": "React",
    "redux": "Redux",
    "react-and-redux": "React와 Redux",
    "data-visualization": "데이터 시각화",
    "data-visualization-with-d3": "D3로 데이터 시각화",
    "json-apis-and-ajax": "JSON, API, Ajax",
    "apis-and-microservices": "API 및 마이크로서비스",
    "managing-packages-with-npm": "NPM 패키지 관리",
    "basic-node-and-express": "Node.js와 Express 기초",
    "mongodb-and-mongoose": "MongoDB와 Mongoose",
    "quality-assurance-and-testing-with-chai": "Chai로 QA 및 테스팅",
    "advanced-node-and-express": "Node.js와 Express 심화",
    "quality-assurance": "품질 보증",
    "scientific-computing-with-python": "Python 과학 컴퓨팅",
    "python-for-everybody": "Python 기초",
    "data-analysis-with-python": "Python 데이터 분석",
    "data-analysis-with-python-course": "Python 데이터 분석 코스",
    "information-security": "정보 보안",
    "information-security-with-helmetjs": "HelmetJS로 정보 보안",
    "python-and-django": "Python과 Django",
    "machine-learning-with-python": "Python 머신러닝",
    "machine-learning-with-python-course": "Python 머신러닝 코스",
    "coding-interview-prep": "코딩 인터뷰 준비",
    "algorithms": "알고리즘",
    "data-structures": "자료구조",
    "take-home-projects": "과제 프로젝트",
    "rosetta-code": "로제타 코드",
    "project-euler": "프로젝트 오일러",
    "legacy-responsive-web-design": "Legacy 반응형 웹 디자인",
    "legacy-javascript-algorithms-and-data-structures": "Legacy JavaScript 알고리즘",
    "legacy-data-visualization": "Legacy 데이터 시각화",
    "legacy-back-end-development-and-apis": "Legacy 백엔드 개발",
    "legacy-information-security-and-quality-assurance": "Legacy 정보 보안 및 QA",
    "the-dom": "DOM",
    "react-with-json-placeholder-api": "JSON Placeholder API와 React",
    "tensorflow": "TensorFlow",
    "natural-language-processing-with-python": "Python 자연어 처리",
    "how-neural-networks-work": "신경망의 작동 원리",
    "colab-by-google": "Google Colab",
    "certificate": "인증서",
    "project": "프로젝트",
    "review": "복습",
    "quiz": "퀴즈",
    "lecture": "강의",
    "workshop": "워크숍",
    "lab": "실습",
    "challenge": "챌린지",
    "step": "단계",
    "portfolio": "포트폴리오",
    "vscode": "VS Code",
    "curriculum": "커리큘럼",
    "frontend": "프론트엔드",
    "backend": "백엔드",
    "fullstack": "풀스택",
    "database": "데이터베이스",
    "algorithm": "알고리즘",
    "interview": "인터뷰",
    "devops": "데브옵스",
    "blockchain": "블록체인",
    "mobile": "모바일",
    "security": "보안",
    "cloud": "클라우드",
    "testing": "테스팅",
    "debug": "디버그",
    "async": "비동기",
    "promises": "프로미스",
    "closure": "클로저",
    "prototype": "프로토타입",
    "class": "클래스",
    "module": "모듈",
    "variable": "변수",
    "function": "함수",
    "array": "배열",
    "object": "객체",
    "string": "문자열",
    "number": "숫자",
    "boolean": "불리언",
    "loop": "반복문",
    "condition": "조건문",
    "operator": "연산자",
    "html": "HTML",
    "css": "CSS",
    "javascript": "JavaScript",
    "python": "Python",
    "node": "Node.js",
    "react": "React",
    "vue": "Vue.js",
    "angular": "Angular",
    "django": "Django",
    "flask": "Flask",
    "sql": "SQL",
    "nosql": "NoSQL",
    "api": "API",
    "rest": "REST",
    "graphql": "GraphQL",
    "docker": "Docker",
    "git": "Git",
    "github": "GitHub",
    "linux": "Linux",
    "command-line": "명령줄",
    "terminal": "터미널",
    "markdown": "마크다운",
    "json": "JSON",
    "regex": "정규식",
    "dom": "DOM",
    "event": "이벤트",
    "form": "폼",
    "input": "입력",
    "output": "출력",
    "image": "이미지",
    "link": "링크",
    "table": "테이블",
    "list": "목록",
    "navigation": "네비게이션",
    "layout": "레이아웃",
    "responsive": "반응형",
    "mobile-first": "모바일 우선",
    "accessibility": "접근성",
    "performance": "성능",
    "optimization": "최적화",
    "seo": "SEO",
    "deployment": "배포",
    "testing": "테스트",
    "debugging": "디버깅",
    "version-control": "버전 관리",
    "authentication": "인증",
    "authorization": "권한",
    "encryption": "암호화",
    "middleware": "미들웨어",
    "routing": "라우팅",
    "state": "상태",
    "props": "프롭스",
    "component": "컴포넌트",
    "hook": "훅",
    "effect": "효과",
    "context": "컨텍스트",
    "reducer": "리듀서",
    "store": "스토어",
    "action": "액션",
    "dispatch": "디스패치",
    "selector": "셀렉터",
    "thunk": "땡크",
    "saga": "사가",
    "observable": "옵저버블",
    "rxjs": "RxJS",
    "typescript": "TypeScript",
    "jsx": "JSX",
    "webpack": "Webpack",
    "babel": "Babel",
    "eslint": "ESLint",
    "prettier": "Prettier",
    "jest": "Jest",
    "mocha": "Mocha",
    "chai": "Chai",
    "cypress": "Cypress",
    "playwright": "Playwright",
    "vite": "Vite",
    "nextjs": "Next.js",
    "nuxt": "Nuxt",
    "gatsby": "Gatsby",
    "astro": "Astro",
    "tailwind": "Tailwind CSS",
    "bootstrap": "Bootstrap",
    "material-ui": "Material UI",
    "ant-design": "Ant Design",
    "chakra": "Chakra UI",
    "shadcn": "shadcn/ui",
    "threejs": "Three.js",
    "d3": "D3.js",
    "chart": "차트",
    "animation": "애니메이션",
    "transition": "트랜지션",
    "transform": "변환",
    "flexbox": "플렉스박스",
    "grid": "그리드",
    "float": "플로트",
    "position": "포지션",
    "display": "디스플레이",
    "box-model": "박스 모델",
    "typography": "타이포그래피",
    "color": "색상",
    "gradient": "그라디언트",
    "shadow": "그림자",
    "border": "테두리",
    "margin": "마진",
    "padding": "패딩",
    "width": "너비",
    "height": "높이",
    "media-query": "미디어 쿼리",
    "breakpoint": "브레이크포인트",
    "pseudo-class": "의사 클래스",
    "pseudo-element": "의사 요소",
    "variable": "변수",
    "scope": "스코프",
    "hoisting": "호이스팅",
    "closure": "클로저",
    "prototype": "프로토타입",
    "class": "클래스",
    "extends": "상속",
    "super": "super",
    "constructor": "생성자",
    "getter": "게터",
    "setter": "세터",
    "static": "정적",
    "this": "this",
    "new": "new",
    "instance": "인스턴스",
    "method": "메서드",
    "property": "속성",
    "key": "키",
    "value": "값",
    "index": "인덱스",
    "length": "길이",
    "push": "push",
    "pop": "pop",
    "shift": "shift",
    "unshift": "unshift",
    "map": "map",
    "filter": "filter",
    "reduce": "reduce",
    "forEach": "forEach",
    "find": "find",
    "some": "some",
    "every": "every",
    "sort": "sort",
    "slice": "slice",
    "splice": "splice",
    "concat": "concat",
    "join": "join",
    "split": "split",
    "replace": "replace",
    "match": "match",
    "test": "test",
    "search": "search",
    "includes": "includes",
    "startsWith": "startsWith",
    "endsWith": "endsWith",
    "toUpperCase": "toUpperCase",
    "toLowerCase": "toLowerCase",
    "trim": "trim",
    "parseInt": "parseInt",
    "parseFloat": "parseFloat",
    "typeof": "typeof",
    "instanceof": "instanceof",
    "delete": "delete",
    "void": "void",
    "typeof": "typeof",
    "yield": "yield",
    "await": "await",
    "async": "async",
    "from": "from",
    "of": "of",
    "in": "in",
    "with": "with",
    "global": "전역",
    "local": "지역",
    "block": "블록",
    "error": "에러",
    "exception": "예외",
    "try": "try",
    "catch": "catch",
    "finally": "finally",
    "throw": "throw",
    "import": "import",
    "export": "export",
    "default": "기본",
    "name": "이름",
    "type": "타입",
    "interface": "인터페이스",
    "generic": "제네릭",
    "enum": "열거형",
    "tuple": "튜플",
    "union": "유니온",
    "intersection": "교차",
    "never": "never",
    "unknown": "unknown",
    "any": "any",
    "void": "void",
    "null": "null",
    "undefined": "undefined",
    "boolean": "boolean",
    "number": "number",
    "string": "string",
    "symbol": "symbol",
    "bigint": "bigint",
    "object": "object",
    "array": "array",
    "function": "function",
    "class": "class",
    "module": "module",
    "namespace": "namespace",
    "declare": "declare",
    "abstract": "abstract",
    "readonly": "readonly",
    "private": "private",
    "protected": "protected",
    "public": "public",
    "static": "static",
    "implements": "implements",
    "extends": "extends",
    "satisfies": "satisfies",
    "keyof": "keyof",
    "typeof": "typeof",
    "infer": "infer",
    "conditional": "조건부",
    "mapped": "매핑된",
    "template": "템플릿",
    "literal": "리터럴",
    "recursive": "재귀",
    "tuple": "튜플",
    "record": "레코드",
    "pick": "Pick",
    "omit": "Omit",
    "partial": "Partial",
    "required": "Required",
    "readonly": "Readonly",
    "utility": "유틸리티",
    "helper": "헬퍼",
    "decorator": "데코레이터",
    "reflect": "Reflect",
    "proxy": "Proxy",
    "symbol": "Symbol",
    "iterator": "이터레이터",
    "generator": "제너레이터",
    "promise": "프로미스",
    "observable": "Observable",
    "subject": "Subject",
    "behavior": "Behavior",
    "replay": "Replay",
    "socket": "소켓",
    "web": "웹",
    "http": "HTTP",
    "https": "HTTPS",
    "ssl": "SSL",
    "tls": "TLS",
    "dns": "DNS",
    "cdn": "CDN",
    "url": "URL",
    "uri": "URI",
    "query": "쿼리",
    "params": "파라미터",
    "header": "헤더",
    "body": "바디",
    "status": "상태",
    "method": "메서드",
    "get": "GET",
    "post": "POST",
    "put": "PUT",
    "patch": "PATCH",
    "delete": "DELETE",
    "options": "OPTIONS",
    "head": "HEAD",
    "cookie": "쿠키",
    "session": "세션",
    "token": "토큰",
    "jwt": "JWT",
    "oauth": "OAuth",
    "cors": "CORS",
    "csrf": "CSRF",
    "xss": "XSS",
    "sql-injection": "SQL 인젝션",
    "cache": "캐시",
    "memory": "메모리",
    "disk": "디스크",
    "network": "네트워크",
    "thread": "스레드",
    "process": "프로세스",
    "worker": "워커",
    "cluster": "클러스터",
    "load": "로드",
    "balance": "밸런스",
    "proxy": "프록시",
    "gateway": "게이트웨이",
    "firewall": "방화벽",
    "container": "컨테이너",
    "kubernetes": "쿠버네티스",
    "pod": "파드",
    "service": "서비스",
    "deployment": "배포",
    "replica": "레플리카",
    "scaling": "스케일링",
    "monitoring": "모니터링",
    "logging": "로깅",
    "alert": "알림",
    "dashboard": "대시보드",
    "metric": "메트릭",
    "trace": "트레이스",
    "span": "스팬",
    "health": "헬스",
    "check": "체크",
    "readiness": "준비",
    "liveness": "활성",
    "startup": "시작",
    "shutdown": "종료",
    "graceful": "우아한",
    "degradation": "성능 저하",
    "failover": "페일오버",
    "recovery": "복구",
    "backup": "백업",
    "restore": "복원",
    "disaster": "재해",
    "business": "비즈니스",
    "continuity": "연속성",
    "sla": "SLA",
    "slo": "SLO",
    "sli": "SLI",
    "agile": "애자일",
    "scrum": "스크럼",
    "kanban": "칸반",
    "sprint": "스프린트",
    "backlog": "백로그",
    "epic": "에픽",
    "story": "스토리",
    "task": "태스크",
    "bug": "버그",
    "feature": "기능",
    "release": "릴리즈",
    "deploy": "배포",
    "rollback": "롤백",
    "hotfix": "핫픽스",
    "patch": "패치",
    "version": "버전",
    "tag": "태그",
    "branch": "브랜치",
    "merge": "병합",
    "rebase": "리베이스",
    "conflict": "충돌",
    "resolve": "해결",
    "stash": "스태시",
    "cherry-pick": "체리픽",
    "amend": "수정",
    "squash": "스쿼시",
    "pr": "PR",
    "issue": "이슈",
    "milestone": "마일스톤",
    "project": "프로젝트",
    "board": "보드",
    "card": "카드",
    "column": "컬럼",
    "swimlane": "스윔레인",
    "workflow": "워크플로우",
    "pipeline": "파이프라인",
    "ci": "CI",
    "cd": "CD",
    "build": "빌드",
    "test": "테스트",
    "lint": "린트",
    "format": "포맷",
    "compile": "컴파일",
    "transpile": "트랜스파일",
    "bundle": "번들",
    "minify": "축소",
    "uglify": "난독화",
    "tree-shaking": "트리 쉐이킹",
    "code-splitting": "코드 분할",
    "lazy-loading": "지연 로딩",
    "ssr": "SSR",
    "csr": "CSR",
    "ssg": "SSG",
    "isr": "ISR",
    "hydration": "하이드레이션",
    "rehydration": "리하이드레이션",
    "prefetch": "프리페치",
    "preload": "프리로드",
    "critical": "크리티컬",
    "above-fold": "접힌 부분 위",
    "below-fold": "접힌 부분 아래",
    "lcp": "LCP",
    "fid": "FID",
    "cls": "CLS",
    "inp": "INP",
    "tti": "TTI",
    "fcp": "FCP",
    "si": "SI",
    "tbt": "TBT",
    "core-web-vitals": "핵심 웹 바이탈",
    "web-vitals": "웹 바이탈",
    "performance": "성능",
    "audit": "감사",
    "score": "점수",
    "opportunity": "기회",
    "diagnostic": "진단",
    "budget": "예산",
    "budget": "예산",
    "metric": "메트릭",
    "measure": "측정",
    "observe": "관찰",
    "analyze": "분석",
    "report": "보고서",
    "insight": "인사이트",
    "trend": "트렌드",
    "pattern": "패턴",
    "anti-pattern": "안티패턴",
    "refactor": "리팩터",
    "optimize": "최적화",
    "simplify": "단순화",
    "modularize": "모듈화",
    "decouple": "분리",
    "encapsulate": "캡슐화",
    "abstract": "추상화",
    "inherit": "상속",
    "polymorph": "다형성",
    "compose": "구성",
    "delegate": "위임",
    "aggregate": "집계",
    "associate": "연관",
    "dependency": "의존성",
    "injection": "주입",
    "inversion": "역전",
    "principle": "원칙",
    "solid": "SOLID",
    "single-responsibility": "단일 책임",
    "open-closed": "개방-폐쇄",
    "liskov-substitution": "리스코프 치환",
    "interface-segregation": "인터페이스 분리",
    "dependency-inversion": "의존성 역전",
    "dry": "DRY",
    "kiss": "KISS",
    "yagni": "YAGNI",
    "composition": "구성",
    "aggregation": "집합",
    "cohesion": "응집도",
    "coupling": "결합도",
    "fan-out": "팬아웃",
    "fan-in": "팬인",
    "complexity": "복잡도",
    "cyclomatic": "순환",
    "cognitive": "인지",
    "maintainability": "유지보수성",
    "readability": "가독성",
    "testability": "테스트 용이성",
    "scalability": "확장성",
    "reliability": "신뢰성",
    "availability": "가용성",
    "durability": "내구성",
    "consistency": "일관성",
    "atomicity": "원자성",
    "isolation": "격리성",
    "durability": "지속성",
    "acid": "ACID",
    "base": "BASE",
    "cap": "CAP",
    "consensus": "합의",
    "quorum": "쿼럼",
    "leader": "리더",
    "follower": "팔로워",
    "candidate": "후보",
    "term": "텀",
    "heartbeat": "하트비트",
    "timeout": "타임아웃",
    "retry": "재시도",
    "backoff": "백오프",
    "circuit-breaker": "서킷 브레이커",
    "bulkhead": "벌크헤드",
    "rate-limit": "속도 제한",
    "throttle": "스로틀",
    "debounce": "디바운스",
    "memoize": "메모이제이션",
    "cache": "캐시",
    "buffer": "버퍼",
    "stream": "스트림",
    "pipe": "파이프",
    "transform": "변환",
    "encode": "인코딩",
    "decode": "디코딩",
    "compress": "압축",
    "decompress": "압축 해제",
    "serialize": "직렬화",
    "deserialize": "역직렬화",
    "parse": "파싱",
    "stringify": "문자열화",
    "format": "포맷",
    "validate": "검증",
    "sanitize": "정화",
    "escape": "이스케이프",
    "unescape": "언이스케이프",
    "encode": "인코딩",
    "decode": "디코딩",
    "hash": "해시",
    "salt": "솔트",
    "pepper": "페퍼",
    "encrypt": "암호화",
    "decrypt": "복호화",
    "sign": "서명",
    "verify": "검증",
    "certificate": "인증서",
    "key": "키",
    "pair": "쌍",
    "public": "공개",
    "private": "비공개",
    "secret": "비밀",
    "password": "비밀번호",
    "pin": "PIN",
    "otp": "OTP",
    "mfa": "MFA",
    "2fa": "2FA",
    "biometric": "생체 인식",
    "face": "얼굴",
    "fingerprint": "지문",
    "voice": "음성",
    "iris": "홍채",
    "retina": "망막",
    "gesture": "제스처",
    "pattern": "패턴",
    "swipe": "스와이프",
    "tap": "탭",
    "double-tap": "더블 탭",
    "long-press": "길게 누르기",
    "pinch": "핀치",
    "zoom": "줌",
    "rotate": "회전",
    "scroll": "스크롤",
    "drag": "드래그",
    "drop": "드롭",
    "hover": "호버",
    "focus": "포커스",
    "blur": "블러",
    "active": "활성",
    "disabled": "비활성",
    "enabled": "활성화",
    "visible": "보임",
    "hidden": "숨김",
    "show": "보이기",
    "hide": "숨기기",
    "toggle": "토글",
    "switch": "스위치",
    "button": "버튼",
    "link": "링크",
    "menu": "메뉴",
    "toolbar": "툴바",
    "sidebar": "사이드바",
    "header": "헤더",
    "footer": "푸터",
    "main": "메인",
    "section": "섹션",
    "article": "아티클",
    "aside": "사이드",
    "figure": "피겨",
    "caption": "캡션",
    "table": "테이블",
    "row": "행",
    "column": "열",
    "cell": "셀",
    "form": "폼",
    "field": "필드",
    "label": "레이블",
    "input": "입력",
    "select": "선택",
    "option": "옵션",
    "checkbox": "체크박스",
    "radio": "라디오",
    "range": "범위",
    "color": "색상",
    "date": "날짜",
    "time": "시간",
    "datetime": "날짜시간",
    "week": "주",
    "month": "월",
    "year": "년",
    "file": "파일",
    "upload": "업로드",
    "download": "다운로드",
    "search": "검색",
    "filter": "필터",
    "sort": "정렬",
    "order": "순서",
    "group": "그룹",
    "category": "카테고리",
    "tag": "태그",
    "badge": "배지",
    "icon": "아이콘",
    "emoji": "이모지",
    "avatar": "아바타",
    "thumbnail": "썸네일",
    "placeholder": "플레이스홀더",
    "tooltip": "툴팁",
    "popover": "팝오버",
    "modal": "모달",
    "dialog": "다이얼로그",
    "alert": "알림",
    "confirm": "확인",
    "prompt": "프롬프트",
    "notification": "알림",
    "toast": "토스트",
    "snackbar": "스낵바",
    "drawer": "드로어",
    "sheet": "시트",
    "panel": "패널",
    "accordion": "아코디언",
    "tabs": "탭",
    "steps": "단계",
    "wizard": "위자드",
    "carousel": "캐러셀",
    "slider": "슬라이더",
    "progress": "진행",
    "spinner": "스피너",
    "skeleton": "스켈레톤",
    "shimmer": "쉬머",
    "empty": "빈 상태",
    "state": "상태",
    "error": "에러",
    "success": "성공",
    "warning": "경고",
    "info": "정보",
    "primary": "기본",
    "secondary": "보조",
    "accent": "강조",
    "neutral": "중립",
    "dark": "어두움",
    "light": "밝음",
    "inverse": "역방향",
    "outline": "아웃라인",
    "solid": "솔리드",
    "ghost": "고스트",
    "link": "링크",
    "text": "텍스트",
    "icon": "아이콘",
    "circle": "원형",
    "square": "사각형",
    "rounded": "둥근",
    "pill": "알약형",
    "shadow": "그림자",
    "elevation": "고도",
    "z-index": "Z-인덱스",
    "stack": "스택",
    "layer": "레이어",
    "depth": "깊이",
    "perspective": "원근",
    "3d": "3D",
    "transform": "변환",
    "translate": "이동",
    "rotate": "회전",
    "scale": "크기",
    "skew": "기울임",
    "matrix": "매트릭스",
    "origin": "원점",
    "center": "중앙",
    "top": "상단",
    "bottom": "하단",
    "left": "왼쪽",
    "right": "오른쪽",
    "start": "시작",
    "end": "끝",
    "before": "이전",
    "after": "이후",
    "first": "첫번째",
    "last": "마지막",
    "nth": "N번째",
    "even": "짝수",
    "odd": "홀수",
    "child": "자식",
    "parent": "부모",
    "sibling": "형제",
    "ancestor": "조상",
    "descendant": "자손",
    "selector": "선택자",
    "combinator": "결합자",
    "pseudo": "의사",
    "attribute": "속성",
    "class": "클래스",
    "id": "ID",
    "type": "타입",
    "universal": "전체",
    "specificity": "특이성",
    "cascade": "캐스케이드",
    "inherit": "상속",
    "initial": "초기",
    "unset": "해제",
    "revert": "되돌림",
    "important": "중요",
    "override": "재정의",
    "fallback": "폴백",
    "alternative": "대체",
    "prefix": "접두사",
    "suffix": "접미사",
    "vendor": "벤더",
    "browser": "브라우저",
    "engine": "엔진",
    "webkit": "WebKit",
    "blink": "Blink",
    "gecko": "Gecko",
    "trident": "Trident",
    "edge": "Edge",
    "chrome": "Chrome",
    "firefox": "Firefox",
    "safari": "Safari",
    "opera": "Opera",
    "ie": "IE",
    "mobile": "모바일",
    "desktop": "데스크탑",
    "tablet": "태블릿",
    "laptop": "노트북",
    "smartphone": "스마트폰",
    "watch": "워치",
    "tv": "TV",
    "console": "콘솔",
    "printer": "프린터",
    "screen": "화면",
    "speech": "음성",
    "braille": "점자",
    "projection": "프로젝션",
    "all": "전체",
    "portrait": "세로",
    "landscape": "가로",
    "orientation": "방향",
    "resolution": "해상도",
    "dpi": "DPI",
    "pixel": "픽셀",
    "rem": "rem",
    "em": "em",
    "percent": "퍼센트",
    "viewport": "뷰포트",
    "vh": "vh",
    "vw": "vw",
    "vmin": "vmin",
    "vmax": "vmax",
    "ch": "ch",
    "ex": "ex",
    "content": "콘텐츠",
    "container": "컨테이너",
    "wrapper": "래퍼",
    "box": "박스",
    "item": "아이템",
    "element": "요소",
    "node": "노드",
    "tree": "트리",
    "root": "루트",
    "leaf": "리프",
    "branch": "브랜치",
    "path": "경로",
    "file": "파일",
    "folder": "폴더",
    "directory": "디렉토리",
    "home": "홈",
    "workspace": "작업 공간",
    "project": "프로젝트",
    "solution": "솔루션",
    "package": "패키지",
    "module": "모듈",
    "library": "라이브러리",
    "framework": "프레임워크",
    "tool": "도구",
    "utility": "유틸리티",
    "plugin": "플러그인",
    "extension": "확장",
    "addon": "애드온",
    "theme": "테마",
    "template": "템플릿",
    "boilerplate": "보일러플레이트",
    "starter": "스타터",
    "seed": "시드",
    "scaffold": "스캐폴드",
    "generator": "제너레이터",
    "config": "설정",
    "setting": "설정",
    "preference": "선호",
    "option": "옵션",
    "feature": "기능",
    "flag": "플래그",
    "env": "환경",
    "development": "개발",
    "staging": "스테이징",
    "production": "운영",
    "local": "로컬",
    "remote": "원격",
    "server": "서버",
    "client": "클라이언트",
    "peer": "피어",
    "host": "호스트",
    "guest": "게스트",
    "agent": "에이전트",
    "broker": "브로커",
    "queue": "큐",
    "topic": "토픽",
    "exchange": "교환",
    "binding": "바인딩",
    "channel": "채널",
    "connection": "연결",
    "session": "세션",
    "transaction": "트랜잭션",
    "lock": "잠금",
    "deadlock": "데드락",
    "race": "경쟁",
    "condition": "조건",
    "critical": "크리티컬",
    "section": "섹션",
    "region": "리전",
    "zone": "존",
    "domain": "도메인",
    "subdomain": "서브도메인",
    "hostname": "호스트명",
    "port": "포트",
    "protocol": "프로토콜",
    "scheme": "스킴",
    "authority": "권한",
    "fragment": "프래그먼트",
    "anchor": "앵커",
    "origin": "오리진",
    "referer": "리퍼러",
    "user-agent": "사용자 에이전트",
    "crawler": "크롤러",
    "bot": "봇",
    "spider": "스파이더",
    "index": "인덱스",
    "crawl": "크롤링",
    "scrape": "스크래핑",
    "scraper": "스크래퍼",
    "webhook": "웹훅",
    "callback": "콜백",
    "endpoint": "엔드포인트",
    "route": "라우트",
    "handler": "핸들러",
    "listener": "리스너",
    "emitter": "이미터",
    "event": "이벤트",
    "signal": "시그널",
    "interrupt": "인터럽트",
    "dispatch": "디스패치",
    "broadcast": "브로드캐스트",
    "multicast": "멀티캐스트",
    "unicast": "유니캐스트",
    "anycast": "애니캐스트",
    "request": "요청",
    "response": "응답",
    "subscribe": "구독",
    "publish": "발행",
    "produce": "생산",
    "consume": "소비",
    "producer": "생산자",
    "consumer": "소비자",
    "supplier": "공급자",
    "processor": "처리기",
    "worker": "작업자",
    "job": "작업",
    "task": "작업",
    "schedule": "스케줄",
    "cron": "크론",
    "trigger": "트리거",
    "action": "액션",
    "operation": "연산",
    "instruction": "명령",
    "command": "명령",
    "query": "질의",
    "mutation": "변이",
    "subscription": "구독",
    "resolver": "리졸버",
    "schema": "스키마",
    "type": "타입",
    "input": "입력",
    "output": "출력",
    "field": "필드",
    "argument": "인자",
    "directive": "지시자",
    "enum": "열거형",
    "scalar": "스칼라",
    "interface": "인터페이스",
    "union": "유니온",
    "fragment": "프래그먼트",
    "variable": "변수",
    "operation": "연산",
    "selection": "선택",
    "mutation": "변이",
    "subscription": "구독",
    "introspection": "내성",
    "validation": "검증",
    "execution": "실행",
    "error": "에러",
    "nullable": "널 가능",
    "non-null": "널 불가",
    "list": "목록",
    "required": "필수",
    "optional": "선택",
    "default": "기본",
    "deprecated": "비권장",
    "specification": "명세",
    "standard": "표준",
    "convention": "관례",
    "practice": "방법",
    "guide": "가이드",
    "tutorial": "튜토리얼",
    "documentation": "문서",
    "reference": "참조",
    "manual": "매뉴얼",
    "readme": "README",
    "changelog": "변경 로그",
    "roadmap": "로드맵",
    "faq": "FAQ",
    "wiki": "위키",
    "glossary": "용어집",
    "api-docs": "API 문서",
    "sdk": "SDK",
    "cli": "CLI",
    "gui": "GUI",
    "ide": "IDE",
    "editor": "편집기",
    "terminal": "터미널",
    "shell": "쉘",
    "prompt": "프롬프트",
    "command": "명령어",
    "argument": "인수",
    "option": "옵션",
    "parameter": "매개변수",
    "flag": "플래그",
    "switch": "스위치",
    "alias": "별칭",
    "shortcut": "단축키",
    "keybinding": "키 바인딩",
    "hotkey": "단축키",
    "shortcut": "바로가기",
    "accelerator": "가속기",
    "mnemonic": "니모닉",
    "gesture": "제스처",
    "combo": "콤보",
    "sequence": "시퀀스",
    "chord": "코드",
    "modifier": "수정자",
    "control": "컨트롤",
    "alt": "Alt",
    "shift": "Shift",
    "meta": "Meta",
    "command": "Command",
    "option": "Option",
    "function": "Function",
    "escape": "Escape",
    "enter": "Enter",
    "tab": "Tab",
    "space": "Space",
    "backspace": "Backspace",
    "delete": "Delete",
    "insert": "Insert",
    "home": "Home",
    "end": "End",
    "page-up": "Page Up",
    "page-down": "Page Down",
    "arrow": "화살표",
    "up": "위",
    "down": "아래",
    "left": "왼쪽",
    "right": "오른쪽",
    "numpad": "숫자패드",
    "numeric": "숫자",
    "alphabetical": "알파벳",
    "alphanumeric": "영숫자",
    "punctuation": "문장부호",
    "symbol": "기호",
    "character": "문자",
    "letter": "글자",
    "digit": "숫자",
    "whitespace": "공백",
    "newline": "줄바꿈",
    "carriage-return": "캐리지 리턴",
    "line-feed": "라인 피드",
    "tab": "탭",
    "indent": "들여쓰기",
    "dedent": "내어쓰기",
    "alignment": "정렬",
    "justify": "양쪽 정렬",
    "flush": "맞춤",
    "wrap": "줄 바꿈",
    "overflow": "오버플로우",
    "clip": "클립",
    "ellipsis": "말줄임표",
    "truncate": "자르기",
    "break": "중단",
    "continue": "계속",
    "return": "반환",
    "yield": "양보",
    "throw": "던지기",
    "raise": "발생",
    "catch": "잡기",
    "handle": "처리",
    "reject": "거부",
    "resolve": "해결",
    "fulfill": "이행",
    "settle": "정착",
    "pending": "대기",
    "resolved": "해결됨",
    "rejected": "거부됨",
    "fulfilled": "이행됨",
    "settled": "정착됨",
}

data['translations'] = translations

out = 'window.__curriculum = ' + json.dumps(data, ensure_ascii=False) + ';'

with open(data_file, 'w', encoding='utf-8') as f:
    f.write(out)

count = sum(1 for s in data['subjects'] if s['n'] in translations)
print(f"Updated {len(translations)} translations. {count}/{len(data['subjects'])} subjects have names.")
print("Done!")
